spring:
  application:
    name: wealthledger-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/wealthledger
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    open-in-view: false	
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        default_schema: public

logging:
  level:
    root: INFO	
cors:
  allowed-origin: ${FRONTEND_URL}
jwt:
  secret: ${JWT_SECRET}